### ISSUE TITLE
github-lfs quota exceeded

### ISSUE THREAD

**Issue by yamule** [t-oda-ic/afm_refiner#2]
(This is the private account of t-oda-ic)
I'm so sorry.
I didn't know that github-lfs is so uneasy to use...
I will take another way to share parameters.
Please use following url until then. Don't forget to check MD5SUM.
https://process.sakura.ne.jp/myresource/afm_refine_g_weights.zip

**Comment by t-oda-ic** [comment]
Uploaded to
https://figshare.com/articles/online_resource/afm_refine_g_20230110_zip/21856407
